model: o3
architect: true

# model: gemini/gemini-2.5-pro-preview-03-25
# model: claude-opus-4-20250514

auto-test: true
test-cmd: make test

auto-lint: false

auto-commits: false
attribute-committer: false

file:
  - build.rs
  - Cargo.toml
  - readme.md
  - src_templates/models.rs
  - src/highlight.rs
  - src/lib.rs
  - src/main.rs
  - src/types.rs

read:
  - tests/integration_tests.rs
