# model: gemini/gemini-2.5-pro

file:
  - build.rs
  - Cargo.toml
  - readme.md
  - src_templates/models.rs
  - src/highlight.rs
  - src/lib.rs
  - src/main.rs
  - src/types.rs

read:
  - tests/integration_tests.rs
