Output demo.gif

Require time
Require cai

Set Shell "bash"
Set FontSize 18
Set Width 1024
Set Height 768
Set TypingSpeed 0.1
Set Framerate 24


Type "# This is a realtime demo of `cai`"
Sleep 500ms
Enter

Type "# Prompts often finish in less than 1 second! 🚀"
Sleep 800ms
Enter

Type "time cai list fast CLI tools"
Sleep 500ms
Enter
Sleep 5s

Type "time cai how to write simple CLI tool in Rust | mdcat | head -n 24"
Sleep 500ms
Enter
Sleep 15s
